### ISSUE TITLE
Query Cost Estimation

### ISSUE THREAD

**Issue by SanGoku95** [evidence-dev/sqltools-bigquery-driver#19] opened 2023-11-30 10:03 UTC
I'm looking to make a contribution to the project. 

@archiewood have you looked into adding the query cost estimation to the plugin?

<img width="296" alt="image" src="https://github.com/evidence-dev/sqltools-bigquery-driver/assets/17087438/8bc5a6b2-8ca4-48ad-9f97-780ab8a43afe">

```
from google.cloud import bigquery

# Construct a BigQuery client object.
client = bigquery.Client()

# Set your query here
query = """
SELECT name, count
FROM `table`
WHERE state = 'TX'
"""

# Set up the dry run query configuration
job_config = bigquery.QueryJobConfig(dry_run=True, use_query_cache=False)

# API request - dry run query
dry_run_query_job = client.query(query, job_config=job_config)

# A dry run query does not provide a row iterator, only statistics
print(f"This query will process {dry_run_query_job.total_bytes_processed} bytes.")
```

**Comment by archiewood** [comment] 2023-11-30 13:47
Hi @Italosayan

I've briefly looked into it, but not extensively. Contributions are  certainly welcomed!

I think calling the dry run function shouldn't be too bad, similar to your example above.

I suspect the hard part is wiring it up into SQLtools, as it does not have inbuilt functionality to support cost estimation.

We need:
- a way for the user to initiate the dry run
- a way to expose the results of the dry run back to the user


Feel free to reach out on slack if I can help at all.

**Comment by archiewood** [comment] 2023-11-30 13:53
Also I think this is a duplicate of #13 - let's continue over there!

**Closed as not planned** 2023-11-30 13:53 UTC
